# -*- coding: utf-8 -*-
"""Crop Production Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ClezDBjud5XcRLc40zWfI5FdoY6rQj7Q
"""

!pip install --upgrade xee

!pip install -U geemap

import ee

ee.Authenticate()
ee.Initialize(
    project = 'ee-lavibas23',
    opt_url = 'https://earthengine-highvolume.googleapis.com'
)

import geemap
import ee

# Initialize map
Map = geemap.Map()

# Load country boundaries
countries = ee.FeatureCollection("USDOS/LSIB_SIMPLE/2017")

# Select India
roi = countries.filter(ee.Filter.eq('country_na', 'India')).geometry()

# Add to map
Map.addLayer(roi, {}, 'India')
Map.centerObject(roi, 5)

Map

crop = (
    ee.ImageCollection("MODIS/061/MCD12Q1")
    .filterDate('2001','2025')
    .select('LC_Type1')
    .map(
        lambda img: img.eq(12).copyProperties(img, ['system:time_start'])
    )
)

npp = (
    ee.ImageCollection("MODIS/061/MOD17A3HGF")
    .filterDate('2001','2025')
    .select('Npp')
)

collection = (
    npp.linkCollection(crop, 'LC_Type1')
    .map(
        lambda img: img.select('Npp').multiply(0.0001).updateMask(img.select('LC_Type1'))
        .copyProperties(img, ['system:time_start'])
    )
)

collection

import xarray as xr

ds = xr.open_dataset(
    collection,
    engine = 'ee',
    crs = 'EPSG:4326',
    scale = 0.1,
    geometry = roi
)

ds = ds.sortby('time') * 1

ds

total_npp = ds.sum(dim = ['lat','lon'])
df = total_npp.to_dataframe()
df.plot()

df.to_csv('total_npp.csv')

!pip install pymannkendall
!pip install pyhomogeneity

import pymannkendall as mk
import pyhomogeneity as hg

mk_test = mk.original_test(df)
mk_test

hg_test = hg.pettitt_test(df)
hg_test

ds.Npp.plot(
    x = 'lon',
    y = 'lat',
    col = 'time',
    col_wrap = 6,
    robust = True,
    cmap = 'turbo'
)

import numpy as np

def spatial_change(img):
  valid_data = img[~np.isnan(img)]
  if len(valid_data) < 2:
    return np.nan
  return mk.original_test(valid_data).slope

npp_change = xr.apply_ufunc(
    spatial_change,
    ds.Npp,
    input_core_dims = [['time']],
    vectorize = True,
    dask = 'parallelized',
    output_dtypes = [float]
)

npp_change.plot(
    x = 'lon',
    y = 'lat',
    robust = True,
    cmap = 'turbo'
)